---
title: "AirCasting Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(broom)
library(shiny)
library(httr)
library(jsonlite)
library(purrr)
library(stringr)
library(leaflet)
library(shinyWidgets)
```


Mobile
=========================================

input_fixed {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r}
usernames <- c('NYCEJA', 'BLU%2012', 'HabitatMap', 'BCCHE', 'scooby', 'Ana%20BCCHE', 'Ricardo%20Esparza', 'Tasha%20kk', 'lana', 'Wadesworld18', 'El%20Puente%204', 'El%20Puente%205', 'mahdin', 'Asemple', 'patqc')

pickerInput("username_choice", label = h4("Select username:"),
            choices = usernames, multiple = TRUE, selected = usernames, options = list(`actions-box` = TRUE))

```


```{r}
dateRangeInput('dates', label = h4('Choose your start and end date:'), 
               format = 'yyyy-mm-dd', 
               min = "2018-03-01", max = Sys.Date(),
               start = Sys.Date() - 365,
               end = Sys.Date()
               )

```

```{r}
airbeam_data_tidy2 <- read_csv('./data/airbeam_data_tidy.csv')

plot_data <- reactive({
  airbeam_data_tidy2 %>% 
    filter(
      username %in% input$username_choice,
           date %in% input$dates[1]:input$dates[2]
    )
  
})


```



Column{data-width=300}
-----------------------------------------------------------------------

### All Data Points

```{r}
renderPlot({
  plot_data() %>% 
  ggplot(aes(x = date, y = PM2.5, color = username)) + geom_point() +
  labs(
    x = 'Date',
    y = 'PM2.5, ug/m3'
  ) +
   theme(legend.title = element_blank())
  
})



```

### Daily averages by Username

```{r}

renderPlot({
 plot_data() %>% 
   group_by(date, username) %>% 
  mutate(daily_average = mean(PM2.5)) %>% 
  select(date, daily_average, username) %>% 
  distinct() %>% 
  ggplot(aes(x = date, y = daily_average, color = username)) + geom_point() + geom_line() +
  labs(
    x = 'Date',
    y = 'Average PM2.5, ug/m3'
  ) +
  theme(legend.title = element_blank())
  
  
  
  
})




```


Column{data-width=300}
-----------------------------------------------------------------------

### Daily Trend


```{r}
renderTable({
  plot_data() %>% 
    group_by(hour) %>% 
  summarize(hourly_average = mean(PM2.5))
  
}, align = 'c')



```

### The Magic Map

```{r}

loc <- reactive({
  plot_data() %>% 
  mutate(latitude = round(latitude, 3),
         longitude = round(longitude, 3)) %>% 
  group_by(latitude, longitude) %>% 
  summarize(avg_pm = mean(PM2.5))
  
  
})
  

renderLeaflet({
  leaflet(data = loc()) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    lat = ~latitude, lng = ~longitude,
    color = 'green',
    radius = 0.2
  )
  
  
})



```



Data Explorer
=========================================

Column
-----------------------------------------

```{r}
pickerInput("username_data", label = h4("Select username:"),
            choices = usernames, multiple = TRUE, selected = usernames, options = list(`actions-box` = TRUE))



```

```{r}

dateRangeInput('date_range', label = h4('Choose your start and end date:'), 
               format = 'yyyy-mm-dd', 
               min = "2018-03-01", max = Sys.Date(),
               start = Sys.Date() - 365,
               end = Sys.Date()
               )

```


```{r}
DT::renderDataTable({
  plot_data() %>% 
    select(username, id, latitude, longitude, PM2.5) %>% 
    mutate(PM2.5 = round(PM2.5, digits = 2))
  
  
})







```

